### ISSUE TITLE
Define library design.

### ISSUE THREAD

**Issue by LukePearson1** [ZK-Garage/plonk#64]
Currently this library has only an implementation of PLONK. In the coming weeks, we will be using the core functional to power gadgets as discussed in #54, and a hashing library. 
The initial idea was to have these as separate libraries under the organisation. However, given the past difficulty of juggling lots of version updates, I think we should consider placing gadgets and hashing inside this one repo as modules. I see this as a successful approach in many projects. 

It _may_ also help with the exposing of witness values inside of variables, such with the `mod_arith` gadget that would be needed for the implementation of reinforced concrete. However, this warrants more thought wrt the exposing of modules.

WDYT? @bhgomes @lopeetall @CPerezz @NoCtrlZ @tsunrise @julesdesmit @joebebel @EDGDrummond @stechu @iquerejeta @davidnevadoc @drewstone @GhostOfGauss @mathcrypto @markulf

**Comment by bhgomes** [comment]
Yes I believe that the single-repo-multiple-crate approach is optimal especially in this case when we are creating libraries that are directly dependent on each other and have parallel goals instead of orthogonal ones. It helps in our case for developer speed and organization, and also for making integrated test suites. It's also easier to discover and design the right abstractions when all of the related code is local to one workspace instead of being spread across many different repos with different versioning and different branching.

Thats my vote for the cargo workspace model.

For our specific case, we can use `plonk` as the main directory where the core plonk code goes (or it can be called `plonk-core` or something) and then all the other libraries use the `plonk-` prefix like `plonk-gadgets`, `plonk-hashing`, ... etc.

**Comment by ghost** [comment]
Single-repo-multiple-crate. Crates for organizing code, repos for organizing teams/projects.

**Comment by CPerezz** [comment]
hmmm. 

It's the eternal dilema of monorepo vs separated crates.
I'm happy with both as long as we define some guidelines on how we organize that! :)

**Comment by mathcrypto** [comment]
I believe it's the best approach to keep them all in the same repo. Same, I saw many ZK libraries keep gadgets in the same repo and it makes things easier from both an organizational and version updates level.

**Comment by stechu** [comment]
Agreed. Also single-repo-multiple-crates makes CI and testing much easier.
